import {useEffect,useState} from "react";
import api,{BACKEND} from "../api";
export default function Products(){
 const [products,setProducts]=useState([]),[form,setForm]=useState({name:"",price:"",category:"General",description:"",stock:""}),[image,setImage]=useState(null),[editing,setEditing]=useState(null),[error,setError]=useState("");
 const load=()=>api.get("/products").then(r=>setProducts(r.data)).catch(e=>setError(e.response?.data?.message||"Could not load products"));
 useEffect(() => {
  load();
}, []);
 const submit=async e=>{e.preventDefault();const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));if(image)fd.append("image",image);try{if(editing) await api.put(`/products/${editing}`,fd);else await api.post("/products",fd);setForm({name:"",price:"",category:"General",description:"",stock:""});setImage(null);setEditing(null);e.target.reset();load()}catch(e){setError(e.response?.data?.message||"Could not save product")}};
 const edit=p=>{setEditing(p.id);setForm({name:p.name,price:p.price,category:p.category||"General",description:p.description||"",stock:p.stock})};
 const del=async id=>{if(confirm("Delete this product?")){await api.delete(`/products/${id}`);load()}};
 return <main className="container py-5"><div className="page-head"><div><span className="eyebrow">PRODUCT CATALOG</span><h2 className="fw-bold">Manage Products</h2></div></div>{error&&<div className="alert alert-danger">{error}</div>}<div className="row g-4"><div className="col-lg-5"><form className="card border-0 shadow-sm p-4 sticky-lg-top" style={{top:90}} onSubmit={submit}><h5>{editing?"Edit Product":"Add Product"}</h5><label className="mt-3">Product Name</label><input className="form-control" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><label className="mt-3">Price (₹)</label><input type="number" min="0" step="0.01" className="form-control" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/><label className="mt-3">Category</label><input className="form-control" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><label className="mt-3">Description</label><textarea className="form-control" rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="mt-3">Available Quantity</label><input type="number" min="0" className="form-control" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} required/><label className="mt-3">Product Image</label><input type="file" accept="image/*" className="form-control" onChange={e=>setImage(e.target.files[0])}/><button className="btn btn-primary mt-4">{editing?"Update Product":"Add Product"}</button>{editing&&<button type="button" className="btn btn-link" onClick={()=>{setEditing(null);setForm({name:"",price:"",category:"General",description:"",stock:""})}}>Cancel</button>}</form></div><div className="col-lg-7"><div className="row g-3">{products.map(p=><div className="col-md-6" key={p.id}><div className="card product-admin h-100 border-0 shadow-sm">{p.image_url?<img src={BACKEND+p.image_url} className="product-img"/>:<div className="product-placeholder">No Image</div>}<div className="p-3"><div className="d-flex justify-content-between"><h6 className="fw-bold">{p.name}</h6><b>₹{Number(p.price).toFixed(2)}</b></div><small className="text-secondary">{p.category} • Stock: {p.stock}</small><p className="small mt-2">{p.description}</p><div className="d-flex gap-2"><button className="btn btn-sm btn-outline-primary" onClick={()=>edit(p)}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={()=>del(p.id)}>Delete</button></div></div></div></div>)}</div>{!products.length&&<div className="empty">No products yet. Add your first product.</div>}</div></div></main>
}
